### ISSUE TITLE
[cw-multi-test] Add support for stargate messages

### ISSUE THREAD

**Issue by kostovster** [Nolus-Protocol/nolus-money-market#1]
Three of the Cosmwasm messages fall into the stargate feature of the cosmwasm lib. The multi-test (MT) lib does not support them yet. 
Usecase: A Nolus contract generates a stargate sub-message, for example, IbcMsg. The MT App panics when comes across such type of message. 
The particular piece of code is this https://github.com/CosmWasm/cw-multi-test/blob/main/src/app.rs#L796-L805
The same approach as the one taken for custom, staking, distribution, etc should be followed. For reference, look into our custom testing::neutron::Module, and the way the AppBuilder takes it into account.
As a result, prepare a merge request at [https://github.com/CosmWasm/cw-multi-test/](https://github.com/CosmWasm/cw-multi-test/blob/main/src/app.rs#L796-L805) . Discussed that with Bart from Confio.
Re-enable the tests ignored with "No support for stargate CosmosMsg-s at cw-multi-test, "

**Comment by KirilMihaylov** [comment]
Migrated to using Neutron instead of Cosmos/CosmWasm IBC messages, and thus can be considered finished as support for them was added in the tests.
