### ISSUE TITLE
[marketprice] Failure to deserialize alarms skip them

### ISSUE THREAD

**Issue by gmanev7** [Nolus-Protocol/nolus-money-market#20]
PriceHooks::get_affected and PriceHooks::get_hook_denoms filter out Err-s to deserialize from the storage. While that should not occur we have to trigger an error instead.
On a related note, please rename all occurrences of hook to alarm where appropriate.

**Comment by gmanev7** [comment]
PriceHooks::get_affected and PriceHooks::get_hook_denoms filter out Err-s to deserialize from the storage. While that should not occur we have to trigger an error instead.
On a related note, please rename all occurrences of hook to alarm where appropriate.

**Comment by go2bodhi** [comment]
resolved in #19
