### ISSUE TITLE
[platform] introduce BankAccountView::balance()

### ISSUE THREAD

**Issue by kostovster** [Nolus-Protocol/nolus-money-market#3]
Currently, only a `receive<C>()` method is available. When the currency is unknown we have to be able to get the balance in any currency. Hence we need a currency-agnostic method. 
Hint: Use platform::`coin_legacy::from_cosmwasm_any `

**Comment by gmanev7** [comment]
Implemented it over Vec<CwCoin> due to the usecase requirements
