### ISSUE TITLE
On Leaser::quote return a meaningful error when there is no price

### ISSUE THREAD

**Issue by gmanev7** [Nolus-Protocol/nolus-money-market#31]
Currently, we get `rpc error: code = InvalidArgument desc = [Leaser] [Oracle] [Std] Generic error: Querier contract error: codespace: wasm, code: 9: query wasm contract failed: invalid request`

**Comment by KirilMihaylov** [comment]
Fixed in commit: f5c4ab448f6814b7f551d007a045447cf291c038
