### ISSUE TITLE
[lease] opening a new lease should let the customer limit the borrowed amount

### ISSUE THREAD

**Issue by kostovster** [Nolus-Protocol/nolus-money-market#32]
Currently, the process of opening a new lease borrows the maximum amount as configured with the initial liability percent. There is a requirement for providing the customer the flexibility to enter the lease with less liability than the pre-configured.

For example, if the init liability is set to 60% then for a downpayment of 100 USDC we provide a loan of 150 USDC, which is 60% of the total value of 100 + 150.

On opening a new lease, the customer should be able to provide an amount to borrow called `max_loan`. It is an optional argument. When provided, the actual amount to borrow should be equal to the min of `max_loan` and calculated per the initial liability configuration. If not, the existing algorithm applies.

For example, the customer may want to take only 100 USDC turning its lease into one with a 50% liability, or LTV ratio.

**Comment by gmanev7** [comment]
Design hints: (1) supply it as an attribute of the NewLeaseForm and (2) consume it in OpenLoanReq to calculate `borrow_lpn`
