### ISSUE TITLE
[oracle] price calculations for specific currencies should reuse the calculation for all currencies

### ISSUE THREAD

**Issue by gmanev7** [Nolus-Protocol/nolus-money-market#38]
Currently, `oracle::contract::feed::Feeds::calc_prices` still use the inefficient algorithm for price calculations. With the introduction of the more efficient one with `oracle::contract::feed::Feeds::all_prices_iter,` we shall unify and re-use the implementation adopting it in the calculation for specific currencies. Hint: use `Iterator::filter` on the currencies.

**Comment by go2bodhi** [comment]
Not relevant anymore due to #57
