### ISSUE TITLE
Define a New ALL_BTC Short Protocol

### ISSUE THREAD

**Issue by gmanev7** [nolus-protocol/nolus-money-market#384]
### DEX
Osmosis

### LPN
ALL_BTC
    // full ibc route: transfer/channel-0/allBTC
    bank: `ibc/E45CFCB959F4F6D1065B7033EE49A88E606E6AD82E75725219B3D68B0FA89987`
    dex: `factory/osmo1z6r6qdknhgsc0zeracktgpcxf43j6sekq07nw8sxduc9lg0qjjlqfu25e3/alloyed/allBTC`
    decimals: 8

### Lease
USDC_NOBLE
    // full ibc route: transfer/channel-0/transfer/channel-750/uusdc
    bank: `ibc/F5FABF52B54E65064B57BF6DBD8E5FAD22CEE9F4B8A57ADBB20CCD0173AA72A4`
    // full ibc route: transfer/channel-750/uusdc
    dex: `ibc/498A0751C798A0D9A389AA3691123DADA57DAA4FE165D5C75894505B876BA6E4`
    decimals: 6

### Payment
ATOM
    // full ibc route: transfer/channel-0/transfer/channel-0/uatom
    bank: `ibc/6CDD4663F2F09CD62285E2D45891FC149A3568E316CE3EBBE201A71A78A69388`
    // full ibc route: transfer/channel-0/uatom
    dex: `ibc/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2`
    decimals: 6

ST_ATOM
    // full ibc route: transfer/channel-0/transfer/channel-326/stuatom
    bank: `ibc/FCFF8B19C61677F3B78E2A5AE3B4A34A8D23858D16905F253B8438B3AFD07FF8`
    // full ibc route: transfer/channel-326/stuatom
    dex: `ibc/C140AFD542AE77BD7DCC83F13FDD8C5E5BB8C4929785E6EC2F4C636F98F17901`
    decimals: 6

OSMO
    // full ibc route: transfer/channel-0/uosmo
    bank: `ibc/ED07A3391A112B175915CD8FAF43A2DA8E4790EDE12566649D0C2F97716B8518`
    dex: `uosmo`
    decimals: 6

ST_OSMO
    // full ibc route: transfer/channel-0/transfer/channel-326/stuosmo
    bank: `ibc/AF5559D128329B6C753F15481BEC26E533B847A471074703FA4903E7E6F61BA1`
    // full ibc route: transfer/channel-326/stuosmo
    dex: `ibc/D176154B0C63D1F9C6DCFB4F70349EBF2E2B5A87A05902F57A6AE92B863E9AEC`
    decimals: 6

WETH
    // full ibc route: transfer/channel-0/transfer/channel-208/weth-wei
    bank: `ibc/A7C4A3FB19E88ABE60416125F9189DA680800F4CDD14E3C10C874E022BEFF04C`
    // full ibc route: transfer/channel-208/weth-wei
    dex: `ibc/EA1D43981D5C9A1C4AAEA9C23BB1D4FA126BA9BC7020A25E0AE4AA841EA25DC5`
    decimals: 18

AKT
    // full ibc route: transfer/channel-0/transfer/channel-1/uakt
    bank: `ibc/ADC63C00000CA75F909D2BE3ACB5A9980BED3A73B92746E0FCE6C67414055459`
    // full ibc route: transfer/channel-1/uakt
    dex: `ibc/1480B8FD20AD5FCAE81EA87584D269547DD4D436843C1D20F15E00EB64743EF4`
    decimals: 6

INJ
    // full ibc route: transfer/channel-0/transfer/channel-122/inj
    bank: `ibc/4DE84C92C714009D07AFEA7350AB3EC383536BB0FAAD7AF9C0F1A0BEA169304E`
    // full ibc route: transfer/channel-122/inj
    dex: `ibc/64BA6E31FE887D66C6F8F31C7B1A80C7CA179239677B4088BB55F5EA07DBE273`
    decimals: 18

AXL
    // full ibc route: transfer/channel-0/transfer/channel-208/uaxl
    bank: `ibc/1B03A71B8E6F6EF424411DC9326A8E0D25D096E4D2616425CFAF2AF06F0FE717`
    // full ibc route: transfer/channel-208/uaxl
    dex: `ibc/903A61A498756EA560B85A85132D3AEE21B5DEDD41213725D22ABF276EA6945E`
    decimals: 6

USDC_NOBLE
    // full ibc route: transfer/channel-0/transfer/channel-750/uusdc
    bank: `ibc/F5FABF52B54E65064B57BF6DBD8E5FAD22CEE9F4B8A57ADBB20CCD0173AA72A4`
    // full ibc route: transfer/channel-750/uusdc
    dex: `ibc/498A0751C798A0D9A389AA3691123DADA57DAA4FE165D5C75894505B876BA6E4`
    decimals: 6

ALL_BTC
    // full ibc route: transfer/channel-0/allBTC
    bank: `ibc/E45CFCB959F4F6D1065B7033EE49A88E606E6AD82E75725219B3D68B0FA89987`
    dex: `factory/osmo1z6r6qdknhgsc0zeracktgpcxf43j6sekq07nw8sxduc9lg0qjjlqfu25e3/alloyed/allBTC`
    decimals: 8

ALL_SOL
    // full ibc route: transfer/channel-0/allSOL
    bank: `ibc/762E1E45658845A12E214A91C3C05FDFC5951D60404FAADA225A369A96DCD9A9`
    dex: `factory/osmo1n3n75av8awcnw4jl62n3l48e6e4sxqmaf97w5ua6ddu4s475q5qq9udvx4/alloyed/allSOL`
    decimals: 9

ALL_ETH
    // full ibc route: transfer/channel-0/allETH
    bank: `ibc/7879B1CBBD2E07347002334792368E65C11A7D1629297D04B6A2155F557E02D4`
    dex: `factory/osmo1k6c8jln7ejuqwtqmay3yvzrg3kueaczl96pk067ldg8u835w0yhsw27twm/alloyed/allETH`
    decimals: 18

### Swap Tree

```
{
    "data": {
        "tree": {
            "value": [
                0,
                "ALL_BTC"
            ],
            "children": [
                {
                    "value": [
                        2054,
                        "ALL_SOL"
                    ]
                },
                {
                    "value": [
                        1942,
                        "USDC_NOBLE"
                    ],
                    "children": [
                        {
                            "value": [
                                1797,
                                "NLS"
                            ]
                        },
                        {
                            "value": [
                                1948,
                                "ALL_ETH"
                            ]
                        },
                        {
                            "value": [
                                1319,
                                "INJ"
                            ]
                        },
                        {
                            "value": [
                                1251,
                                "ATOM"
                            ],
                            "children": [
                                {
                                    "value": [
                                        1283,
                                        "ST_ATOM"
                                    ]
                                },
                                {
                                    "value": [
                                        1135,
                                        "OSMO"
                                    ],
                                    "children": [
                                        {
                                            "value": [
                                                833,
                                                "ST_OSMO"
                                            ]
                                        },
                                        {
                                            "value": [
                                                1093,
                                                "AKT"
                                            ]
                                        },
                                        {
                                            "value": [
                                                812,
                                                "AXL"
                                            ]
                                        },
                                        {
                                            "value": [
                                                1134,
                                                "WETH"
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    }
}
```

**Comment by gmanev7** [comment]
@metodi96 Please confirm this protocol is going to be on OSMOSIS

**Comment by metodi96** [comment]
@gmanev7 I confirm, edited the task to specify this
