### ISSUE TITLE
Add New Currencies to OSMOSIS-OSMOSIS-USDC_NOBLE

### ISSUE THREAD

**Issue by kostovster** [nolus-protocol/nolus-money-market#385]
### Payment

ALL_BTC
// full ibc route: transfer/channel-0/allBTC
bank: `ibc/ED07A3391A112B175915CD8FAF43A2DA8E4790EDE12566649D0C2F97716B8518`
dex: `factory/osmo1z6r6qdknhgsc0zeracktgpcxf43j6sekq07nw8sxduc9lg0qjjlqfu25e3/alloyed/allBTC`
decimals: 8

ALL_SOL
// full ibc route: transfer/channel-0/allSOL
bank: `ibc/762E1E45658845A12E214A91C3C05FDFC5951D60404FAADA225A369A96DCD9A9`
dex: `factory/osmo1n3n75av8awcnw4jl62n3l48e6e4sxqmaf97w5ua6ddu4s475q5qq9udvx4/alloyed/allSOL`
decimals: 9

ALL_ETH
// full ibc route: transfer/channel-0/allETH
bank: `ibc/7879B1CBBD2E07347002334792368E65C11A7D1629297D04B6A2155F557E02D4`
dex: `factory/osmo1k6c8jln7ejuqwtqmay3yvzrg3kueaczl96pk067ldg8u835w0yhsw27twm/alloyed/allETH`
decimals: 18

### Lease

ALL_BTC
// full ibc route: transfer/channel-0/allBTC
bank: `ibc/ED07A3391A112B175915CD8FAF43A2DA8E4790EDE12566649D0C2F97716B8518`
dex: `factory/osmo1z6r6qdknhgsc0zeracktgpcxf43j6sekq07nw8sxduc9lg0qjjlqfu25e3/alloyed/allBTC`
decimals: 8

ALL_SOL
// full ibc route: transfer/channel-0/allSOL
bank: `ibc/762E1E45658845A12E214A91C3C05FDFC5951D60404FAADA225A369A96DCD9A9`
dex: `factory/osmo1n3n75av8awcnw4jl62n3l48e6e4sxqmaf97w5ua6ddu4s475q5qq9udvx4/alloyed/allSOL`
decimals: 9

ALL_ETH
// full ibc route: transfer/channel-0/allETH
bank: `ibc/7879B1CBBD2E07347002334792368E65C11A7D1629297D04B6A2155F557E02D4`
dex: `factory/osmo1k6c8jln7ejuqwtqmay3yvzrg3kueaczl96pk067ldg8u835w0yhsw27twm/alloyed/allETH`
decimals: 18

**Comment by gmanev7** [comment]
@kostovster Adding these currencies is not sufficient anymore to add them later to the swap tree. We also have to define the other currencies they may go within pairs.

**Comment by metodi96** [comment]
@gmanev7, ALL_BTC is paired with USDC_NOBLE, ALL_SOL is paired with ALL_BTC, ALL_ETH is paired with USDC_NOBLE
