### ISSUE TITLE
Execute Bank Transfer Upon Migration

### ISSUE THREAD

**Issue by kostovster** [nolus-protocol/nolus-money-market#386]
Upon migration, execute bank transfer of funds from `nolus17zjugw5la8fwa0jyca2tqg28upmjyqjwscc2z4fu54s0cdkh724ql4j6r7` to 
`nolus1klq25snxga33mgqvrwruuvvulr99hkugauqdsl`

**Comment by gmanev7** [comment]
In addition to the lease provided in the task description, we have also covered the following leases:

"nolus1q2xsckvufnlz6yynqsm33mrcx2hkajjwyqjxnmxslhyt85mvg9csyzy97z",
"nolus1scvnd78uzl8jwpwtnggy8l4tk56n6fkgg3nw5z5qnhp0tk0nd7uss225rw",
"nolus1d0dc9zqtj9yagd8wkaw23qhw84x4agqxgu39hj7zts0xrzvj9mtqfmtcjy",
"nolus1v2vwau267hn7g3frgnqsshfehtn6d6fnd9j9s0wm3n4t3n4mnecqh77dfp"
