### ISSUE TITLE
[Dispatcher] Add a query for the TVL-to-APR scale and update the init scale

### ISSUE THREAD

**Issue by gmanev7** [nolus-protocol/nolus-money-market#66]
Currently, the scale passed at the dispatcher contract init is only used internally for calculations. For the sake of UI, we need it to be queried. The subtasks here are:
- add a query that returns the scale
- update the initial value of the scale with the one provided here below.
- update the multiplication factor which is currently x1000, i.e. in mini-LPNs,  to x1000x1000x1000, i.e. in hundreds-LPNs

<500k 15%
500k - 1m 14%
1m - 2m 13%
2m - 3m 12%
3m - 4m 11%
4m - 5m 10%
5m - 7.5m 9%
7.5m - 10m 8%
10m - 15m 7%
15m - 20m 6%
20m - 25m 5%
25m - 30m 4%
30m - 40m 3%
\>40m 2%

**Comment by KirilMihaylov** [comment]
Closed by 607eaa04264fb9f8b9bc03fa505cdf47f162aa56, 2e6912e8b86fbf6785868af55af677a8f28cc2b6 and d5cffe94f0cf04ca665a92ee8988359b7aebd604
