### ISSUE TITLE
[Rewards_dispatcher] There are no rewards available for lenders

### ISSUE THREAD

**Issue by desislavva** [nolus-protocol/nolus-money-market#75]
_Env: Dev_
**There are no rewards available for lenders.**

Тhe Rewards_dispatcher contract is set to dispatch rewards every hour. However, rewards to the lpp are not sent automatically.
When sending rewards manually via **distribute_rewards** exec - rewards are delivered successfully.

**Comment by gmanev7** [comment]
not reproducible anymore
