### ISSUE TITLE
Remove the allowance of `elided-lifetimes-in-paths` lint

### ISSUE THREAD

**Issue by gmanev7** [Nolus-Protocol/nolus-money-market#8]
The `elided-lifetimes-in-paths` lint is suppressed in the checks by `lint.sh`. 

Change the code to explicitly specify lifetimes and remove the `-A` from `lint.sh`.

**Comment by gmanev7** [comment]
most of the occurrences of implicit lifetimes would go away once #7 got resolved

**Comment by KirilMihaylov** [comment]
Fixed in main.
